[server]
    network_interface  = "eth0"
    bind_interface     = true
    use_interface_ip   = true

[server.http]
    host               = "localhost"
    port               = 8088
    charset            = "UTF-8"
    gzip               = true
    pprof              = false

#日志
[log]
    directory       = "./storage/logs/"
    level           = 5

[db]
    drive           = "mysql"
    host            = "10.52.161.50"
    port            = "3306"
    user            = "root"
    password        = "root"
    charset         = "utf8mb4"
    database        = "iris"
    timeout         = 3
    max_open_conns  = 128
    max_idle_conns  = 64
    max_conn_ttl    = 60
    debug           = true
#reids
[cache]
    host            = "127.0.0.1"
    port            = 6379
    password        = ""
    database        = 0
    poolsize        = 128

[jwt]
    #jwt key
    secret = "$2a$10$9KvAFraMtXnarydGSbXkqeE0EnTKNI4Uvra7WOgMOCD2NE6RHmVo2"