[server]
    network_interface  = "eth0"
    bind_interface     = true
    use_interface_ip   = true
    charset            = "utf8"

[server.http]
    host               = "localhost"
    port               = 8088
    charset            = "UTF-8"
    gzip               = true
    pprof              = false
[server.http.log]
    directory          = "/Users/knight/go/iris/src/storage/httplogs/"
    level              = 5
    time_format        = "2006-01-02 15:04:05.000"
    color              = false
    terminal           = false

[log]
    directory       = "/Users/knight/go/iris/src/storage/logs/"
    level           = 5

[db]
    drive           = "mysql"
    host            = "127.0.0.1"
    port            = "3306"
    user            = "root"
    password        = "root"
    charset         = "utf8"
    database        = "iris"
    timeout         = 3
    max_open_conns  = 128
    max_idle_conns  = 64
    max_conn_ttl    = 3600
    debug           = true

[cache]
    host            = "127.0.0.1"
    port            = 6379
    password        = ""
    database        = 0
    poolsize        = 128

[jwt]
    secret = "$2a$10$9KvAFraMtXnarydGSbXkqeE0EnTKNI4Uvra7WOgMOCD2NE6RHmVo2"